language: cpp
compiler:
  - gcc
  - clang

sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - cmake
    - g++-4.9
    - clang
    - hdf5-helpers
    - libhdf5-dev
    - octave
    - liboctave-dev

before_install:
#  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
#  - sudo apt-get update;
#  - sudo apt-get install gcc-4.8 g++-4.8 cmake;
#  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20;
  - ${CXX} --version
  - cmake --version
#  - sudo apt-get update -qq;

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - mkdir build && cd build
  - cmake ..
  - cmake --build .

script:
  - cmake --build . --target test
  - cat Testing/Temporary/*.log
