language: cpp
compiler:
  - gcc
  - clang

sudo: required
dist: trusty

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - cmake
    - g++-4.9
    - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libboost-test-dev libeigen3-dev libmatio-dev libhdf5-dev

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - mkdir build
  - cd build
  - cmake ..
  - make VERBOSE=1

script: 
  - make test
